version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=vote
      - POSTGRES_USER=vote_user
      - POSTGRES_PASSWORD=vote123
    networks:
      - app-network

  db_test:
    image: postgres:latest
    container_name: db_test
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=vote_test
      - POSTGRES_USER=vote_user
      - POSTGRES_PASSWORD=vote123
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/aiohttp
    ports:
      - 8000:8000
    links:
      - db
      - db_test
    working_dir: /var/www/aiohttp
    env_file: .env
    depends_on:
      - db
      - db_test
    networks:
      - app-network

networks:
  app-network:
    driver: bridge