version: "3.8"
services:

  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/aiohttp
      - ./db:/var/www/aiohttp/db
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
        - vibhuviesdata:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    labels:
        - co.elastic.logs/module=elasticsearch
        - co.elastic.metrics/module=elasticsearch

  kibana:
      image: docker.elastic.co/kibana/kibana:7.7.0
      container_name: kibana
      ports:
          - 5601:5601
      depends_on:
          - elasticsearch
      environment:
          ELASTICSEARCH_URL: http://elasticsearch:9200
          ELASTICSEARCH_HOSTS: http://elasticsearch:9200

volumes:
  vibhuviesdata:
    driver: local

networks:
  default:
    driver: bridge
    name: app-network
